### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by rsyd29** [yusriltakeuchi/assets_cleaner#1]
#question
Thanks for making this, but how do i use it? This seems to really help me in finding assets that I don't use in my project.

**Comment by yusriltakeuchi** [comment]
this tools is under constructions, you can use it when it's already deployed to pub.dev

**Comment by yusriltakeuchi** [comment]
Helo @rsyd29 you can use this tools now, check this : https://pub.dev/packages/assets_cleaner
